export default {
  titles: {
    sendTokens: 'Try to send any tokens or NFTs via link',
    main: 'Send digital assets<br>encoded in links',
    sendTokensToAddress: 'Scan or copy<br>to send digital assets',
    sendWithMetamask: 'Send digital assets<br>with MetaMask extension',
    shareLink: 'Copy and share the link',
    linkDone: 'Your\'re done!',
    scanCode: 'Scan QR-code to get link',
    multipleLinkes: 'Multiple links',
    analytics: 'Analitycs',
    expiredLinks: 'Expired links',
    wantMoreLinks: 'Want more links?',
    cs: 'Customer service 24/7',
    terms: 'I agree with <a href={{termsHref}}>Terms</a> & <a href={{privacyHref}}>Privacy</a>',
    getYourLink: 'Copy and share the link',
    linkdrop: 'Linkdrop',
    multipleLinks: 'Multiple links & Analytics',
    createShare: 'Fast and simple',
    noGas: 'No gas or any fees',
    tokenTypes: 'ETH, ERC20 & ERC721 tokens',
    yourEmail: 'Your email',
    wantMoreLinksInstruction: 'Request early access to the Linkdrop Dashboard',
    everydayUsers: 'We link everyday users to digital assets',
    seeGit: 'See the Github',
    join: 'Join Community',
    followOnTwitter: 'Follow on Twitter',
    trusted: 'Trusted by Leading Companies and Wallets',
    addManually: 'Add token address manually',
    footerAddManually: '<span>Add manually</span>',
    tokenAddress: 'Token address',
    waitingFor: 'Waiting for {{tokenSymbol}}...',
    errorOccured: 'Some error occured',
    erc721: 'ERC-721',
    erc20: 'ERC-20',
    eth: 'ETH',
    ethAmount: 'ETH to send',
    tokenAmount: '{{symbol}} to send',
    tokenId: 'Token ID',
    beCareful: 'Be careful!',
    chooseAsset: 'Choose asset',
    otherToken: 'Other Token',
    networkNotSupported: 'Network is not supported',
    telegramConnect: 'If you have any troubles—shoot us in <a target="_blank" href="https://t.me/LinkdropOrg">Telegram</a>'
  },
  descriptions: {
    sendTokens: 'Simply send your funds to our secure contract and generate the crypto link',
    massGenerate: 'Linkdrop lets you<br/>mass-generate & track links',
    newLinkInstruction: 'To create a new link—first claim this one',
    sendLinks: 'Linkdrop enables you to send links with included digital assets and onboarding properties',
    bugBountyNote: 'This demo-app is only fit to be used<br>on the Ethereum Rinkeby testnet'
  },
  buttons: {
    continue: 'Continue',
    createLink: 'Create Link',
    copyLink: 'Copy Link',
    close: 'Close',
    tryForFree: 'Try for Free',
    campaign: 'Set Up Campaign',
    learnMore: 'Learn More',
    joinWaitlist: 'Join Waitlist',
    requestAccess: 'Request Access',
    next: 'Next',
    understood: 'Yep, understood'
  },
  errors: {
    addManually: 'Try to add token manually',
    NO_TOKEN_ADDRESS_FOUND: 'No token address found. Please check it, and try again.',
    ERROR_OCCURED_WITH_ERC721: 'Unable to find NFT-token',
    PROBLEM_WITH_EXRTERNAL_LIBRARY: 'Problem with connection to external library API. Please try later',
    NETWORK_NOT_SUPPORTED: 'Switch to {{network}}',
    ERROR_WITH_SIGNATURE_OCCURED: 'Some error occured with Metamask signiture. Please reload page and try again'
  }
}
